### PR TITLE
DNN-9302: fix issues and optimize

### PR DESCRIPTION
**Pull request by sleupold**
- fix schema issue
- improve query by omitting unnecessary join
- reformat for readability

### CODE REVIEW

**Comment by sleupold** [comment]
PR #24 submitted

**Comment by MackeyK24** [comment]
For the love of god... Will someone please tell me how to build and PACKAGE this project. There absolutely NO instructions on how to package the module for DNN install. How do you run the build and package scripts ???

**Comment by eltesoro-dnn** [comment]
@MackeyK24
http://www.dnnsoftware.com/docs/developers/extensions/pack-extension.html
Please let me know if that page helps.

**Comment by MackeyK24** [comment]
I have tried to compile your Dnn.AdminExpereince in 'Release' mode... It compiles fine, BUT IT DOES NOT Create the DNN packages like the LINK you just sent says it should.

The project has a Module.build that BuildScripts that look like it supposed to build the Dnn.Persona module packages... Can you please tell me HOW to package the Dnn.AdminExperience project.

**Comment by bdukes** [comment]
@MackeyK24, I believe I've heard that this is something that @ashishpd and team are currently working on, but it currently requires a bit of setup.  I've done a little bit of looking to try to figure out how they have this setup, but hopefully this gets simpler and better documented.

You can see in a file like [/src/Solution.Build](https://github.com/dnnsoftware/Dnn.AdminExperience.Extensions/blob/1780949d825760ce3ba5811897cb69e1d525fc82/src/Solution.build#L3-L4) that the project expects some files to exist _outside_ of this repository.  So, it looks like perhaps if you clone this repo into the [Dnn.Platform](https://github.com/dnnsoftware/Dnn.Platform) source, at `/Website/DesktopModules/admin/Dnn.PersonaBar`, then it will be able to find those packaging scripts.  You'll also need to figure out getting all of the NuGet references fulfilled.

Hope it helps!

**Comment by ashishpd** [comment]
Can you try compiling using the instructions given in the readme file here: https://github.com/dnnsoftware/Dnn.Platform/releases/download/v9.0.1/DNN_Platform_9.0.1.142_Source.zip

The readme file is inside the zip.

**Comment by MackeyK24** [comment]
That did it :)

All the packages are in /Website/Install/Module folder "OUTSIDE" the
project folder.

**Comment by bdukes** [comment]
@ashishpd that worked for me.  is there something different in the source zip, or just the layout of the projects in the file system?

**Comment by ashishpd** [comment]
@bdukes there is no difference in the source code as such. Minor changes in the build scripts to ensure output .zip files are created at the right location.

**Comment by ashishpd** [comment]
I actually blogged about it as well. @bdukes  can you please review that: http://www.dnnsoftware.com/community-blog/cid/155414/dnn-9-compiling-platform-using-901-source-package

**Comment by bdukes** [comment]
@ashishpd the blog post is straightforward and helpful :+1:, though I'd still like to see a simpler story when cloning the git repo.

**Comment by zyhfish** [comment]
This issue already resolved in DNN-9695.

**Pull request closed without merging**
