### PR TITLE
DNN-7820: set padding right style has higher priority.

### PR DESCRIPTION
**Pull request by zyhfish**

### CODE REVIEW

**Comment by tpluscode** [comment]
Oh, maybe there is a better way than `!important`?

**Comment by zyhfish** [comment]
has to use this as evoq overwrite this style.

**Comment by tpluscode** [comment]
What about a more specific selector? 

Any ideas @ricardodiasc @mean2me ?

**Comment by tpluscode** [comment]
> evoq overwrite this style

Or, maybe the fix belongs to Evoq then?

**Comment by mean2me** [comment]
Probably if we define the rule inside the #users-container selector, it will have priority:
(https://github.com/dnnsoftware/Dnn.AdminExperience.Extensions/blob/da4e4e32e8fd61a1336f4ec7f5b40927bf19af07/src/Modules/Manage/Dnn.PersonaBar.Users/Users.Web/src/components/Body/style.less)

**Pull request closed without merging**
