### PR TITLE
Bug/dnn 20362

### PR DESCRIPTION
**Pull request by Mohtshum**

### CODE REVIEW

**Review by tpluscode — COMMENTED** [review]
Great, I like it in general.

My only question is about the new interface. Why did you name it `IStaticDependecyResolver`?

**Comment by Mohtshum** [comment]
Actually I want that to use for static method calls for different classes as well. Rather then creating a new Interface for each it could be used to wrap their calls.

**Comment by tpluscode** [comment]
Please don't do that. It will potential create a weird "Frankenstein" interface with many unrelated responsibilities. 

Instead we should have dedicated, possibly small interfaces with well-defined functionality.

**Comment by tpluscode** [comment]
I suppose a natural way would be to have a dedicated wrapper for the wrapped types. In this case it's `FriendlyUrlController` and `UrlRewriterUtils`

**Review by tpluscode — APPROVED** [review]
Perfect 👌 

Also, thanks for renaming that parameter. I would have missed it 🥇

**Comment by tpluscode** [comment]
partially fixes #572

**Pull request merged**
