### PR TITLE
DNN-20842 : Update yarn.lock to refer only public MyGet repository.

### PR DESCRIPTION
**Pull request by ricardodiasc**
Fixes #575

### CODE REVIEW

**Comment by bdukes** [comment]
@ricardodiasc I'm seeing a lot of version changes in the lock file, I'm not seeing URL changes.  Can you specify what's supposed to be changing here?

**Comment by tpluscode** [comment]
See for example the resolution for `enzyme-adapter-react-15` (Line 2040) @bdukes. 

The lock file was generated with `npmrc` using the private NPM repository. One mirrors the other hence the resolution URLs. This then cannot be installed on CI because it only accesses the public feeds.

**Comment by bdukes** [comment]
Got it.  👍

**Review by bdukes — APPROVED** [review]
I'd prefer just the URL changes, and version differences being a separate commit, but I don't think it's going to cause any issues.

**Review by tpluscode — APPROVED** [review]

**Pull request merged**
