### PR TITLE
Move CI configuration from Jenkins

### PR DESCRIPTION
**Pull request by tpluscode**
This changes AppVeyor configuration so that builds will be triggered for every PR

### CODE REVIEW

**Comment by tpluscode** [comment]
Please take a look @ahoefling @mitchelsellers

**Comment by SkyeHoefling** [comment]
looks good to me

**Comment by mitchelsellers** [comment]
@ahoefling For tracking, can you do your comment as a true review?

Edit: looks like we don't have proper permissions in this repo...

**Comment by tpluscode** [comment]
Guys, I moved the various scripts that Jenkins currently runs to the AppVeyor's config:

1. Added the yarn script which installs JS packages
1. create nupkg and install packages (added as artifacts)
1. tests now run

One thing you will notice is GitVersion. Don't mind it's now showing `1.5.1`. This would require fixing the branching model first.

**Comment by tpluscode** [comment]
@mitchelsellers please check the permissions again The advisory group team is added with write level.

**Comment by SkyeHoefling** [comment]
The changes look good to me but I am not 100% certain on all the build scripts for this project. I spoke with @mitchelsellers and @ohine and we believe @ohine can handle the review of this one to make sure it is all good.

**Comment by tpluscode** [comment]
> I am not 100% certain on all the build scripts for this project

@ahoefling Are you referring to the msbuild files? Those are the very same scripts which have been used on Jenkins and TeamCity before that. Granted, they could be rewritten to be much simpler but it's nothing new.

**Review by ohine — APPROVED** [review]
This looks good to me, but we might be changing how things are packaged as we continue on the CI tasks for the platform.

**Comment by tpluscode** [comment]
Would you merge this then @ohine ?

> we might be changing how things are packaged as we continue on the CI tasks for the platform.

For all I care, we could (temporarily) keep PB builds on AppVeyor and only build Platform on VSTS. We only have to figure out a way to deliver artifacts which works for us. 

That said, migrating from appveyor.yml to other CI should be a piece of cake :D

**Comment by tpluscode** [comment]
I did a mess of commits here by the way. Definitely should squash.

**Comment by mitchelsellers** [comment]
Closing this due to change to VSTS

**Pull request closed without merging**
